REM Generated from Makefile using 'make make.bat'
..\bin\lcc -c -o arand.o arand.s
..\bin\lcc -c -o asl.o asl.s
..\bin\lcc -c -o asr.o asr.s
..\bin\lcc -c -o cgb.o cgb.s
..\bin\lcc -c -o clock.o clock.s
..\bin\lcc -c -o cpy_data.o cpy_data.s
..\bin\lcc -c -o crt0.o crt0.s
..\bin\lcc -c -o delay.o delay.s
..\bin\lcc -c -o div.o div.s
..\bin\lcc -c -o drawing.o drawing.s
..\bin\lcc -c -o endin.o endin.s
..\bin\lcc -c -o f_ibm_sh.o f_ibm_sh.s
..\bin\lcc -c -o f_italic.o f_italic.s
..\bin\lcc -c -o f_min.o f_min.s
..\bin\lcc -c -o f_spect.o f_spect.s
..\bin\lcc -c -o floor.o floor.s
..\bin\lcc -c -o font.o font.s
..\bin\lcc -c -o fp_long.o fp_long.s
..\bin\lcc -c -o ftou.o ftou.s
..\bin\lcc -c -o get_bk_t.o get_bk_t.s
..\bin\lcc -c -o get_data.o get_data.s
..\bin\lcc -c -o get_prop.o get_prop.s
..\bin\lcc -c -o get_spr.o get_spr.s
..\bin\lcc -c -o get_wi_t.o get_wi_t.s
..\bin\lcc -c -o get_xy_t.o get_xy_t.s
..\bin\lcc -c -o global.o global.s
..\bin\lcc -c -o hiramcpy.o hiramcpy.s
..\bin\lcc -c -o ibmfixed.o ibmfixed.s
..\bin\lcc -c -o init_tt.o init_tt.s
..\bin\lcc -c -o input.o input.s
..\bin\lcc -c -o lreg.o lreg.s
..\bin\lcc -c -o lsr.o lsr.s
..\bin\lcc -c -o macros.o macros.s
..\bin\lcc -c -o malloc-gb.o malloc-gb.s
..\bin\lcc -c -o math.o math.s
..\bin\lcc -c -o memcpy.o memcpy.s
..\bin\lcc -c -o memset.o memset.s
..\bin\lcc -c -o mul.o mul.s
..\bin\lcc -c -o mv_bkg.o mv_bkg.s
..\bin\lcc -c -o mv_spr.o mv_spr.s
..\bin\lcc -c -o mv_win.o mv_win.s
..\bin\lcc -c -o pad.o pad.s
..\bin\lcc -c -o rand.o rand.s
..\bin\lcc -c -o sample.o sample.s
..\bin\lcc -c -o scroll_b.o scroll_b.s
..\bin\lcc -c -o scroll_s.o scroll_s.s
..\bin\lcc -c -o scroll_w.o scroll_w.s
..\bin\lcc -c -o serial.o serial.s
..\bin\lcc -c -o set_bk_t.o set_bk_t.s
..\bin\lcc -c -o set_data.o set_data.s
..\bin\lcc -c -o set_prop.o set_prop.s
..\bin\lcc -c -o set_spr.o set_spr.s
..\bin\lcc -c -o set_wi_t.o set_wi_t.s
..\bin\lcc -c -o set_xy_t.o set_xy_t.s
..\bin\lcc -c -o sgb.o sgb.s
..\bin\lcc -c -o sin_cos.o sin_cos.s
..\bin\lcc -c -o sintable.o sintable.s
..\bin\lcc -c -o sqrt.o sqrt.s
..\bin\lcc -c -o abs.o abs.c
..\bin\lcc -c -o atoi.o atoi.c
..\bin\lcc -c -o atol.o atol.c
..\bin\lcc -c -o digits.o digits.c
..\bin\lcc -c -o gprint.o gprint.c
..\bin\lcc -c -o gprintf.o gprintf.c
..\bin\lcc -c -o gprintln.o gprintln.c
..\bin\lcc -c -o gprintn.o gprintn.c
..\bin\lcc -c -o isalpha.o isalpha.c
..\bin\lcc -c -o isdigit.o isdigit.c
..\bin\lcc -c -o islower.o islower.c
..\bin\lcc -c -o isspace.o isspace.c
..\bin\lcc -c -o isupper.o isupper.c
..\bin\lcc -c -o itoa.o itoa.c
..\bin\lcc -c -o labs.o labs.c
..\bin\lcc -c -o ltoa.o ltoa.c
..\bin\lcc -c -o malloc-block.o malloc-block.c
..\bin\lcc -c -o malloc-list.o malloc-list.c
..\bin\lcc -c -o print.o print.c
..\bin\lcc -c -o printf.o printf.c
..\bin\lcc -c -o println.o println.c
..\bin\lcc -c -o printn.o printn.c
..\bin\lcc -c -o puts.o puts.c
..\bin\lcc -c -o reverse.o reverse.c
..\bin\lcc -c -o scanf.o scanf.c
..\bin\lcc -c -o sprint.o sprint.c
..\bin\lcc -c -o sprintf.o sprintf.c
..\bin\lcc -c -o sprintln.o sprintln.c
..\bin\lcc -c -o sprintn.o sprintn.c
..\bin\lcc -c -o strcat.o strcat.c
..\bin\lcc -c -o strcmp.o strcmp.c
..\bin\lcc -c -o strcpy.o strcpy.c
..\bin\lcc -c -o strlen.o strlen.c
..\bin\lcc -c -o strncat.o strncat.c
..\bin\lcc -c -o strncmp.o strncmp.c
..\bin\lcc -c -o strncpy.o strncpy.c
..\bin\lcc -c -o time.o time.c
..\bin\lcc -c -o tolower.o tolower.c
..\bin\lcc -c -o toupper.o toupper.c
